# Generated by Django 4.2 on 2023-04-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
