# Generated by Django 4.2 on 2023-05-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_app', '0005_channel_business_email_channel_business_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='business_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
