# Generated by Django 4.2 on 2023-05-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel_app', '0007_community'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='community',
            table='comminities',
        ),
    ]
